config/routes.rb
Rails.application.routes.draw do
  devise_for :user
  get '/user', to: redirect("/user/sign_up"), as: "user_sign_up_again"

  root to: "home#index"
  
  resources :univ_classes, only: [:index]

  resources :users, only: [:show] do
    resource :likes, only: [:show]
    resources :univ_classes, only: [:index, :show, :update, :destroy] do
      resource :likes, only: [:create, :destroy]
      collection do
        get :search
      end
    end
  end
  post "/univ_classes/import", to: 'univ_classes#import'
  #/users/:id/univ_classes/search　これはエラー。users/:user_id/univ_classes/searchじゃないとだめ！！idはuniv_class_idと認識されてしまう。注意
  # get "/users/:id/univ_classes/search", to: 'univ_classes#search'
  
  # get '*path', controller: 'application', action: 'render_404'
end

app/controllers/univ_classes_controller.rb
class UnivClassesController < ApplicationController
    before_action :authenticate_user!

    def index
        @user = User.find(current_user.id)
        @univ_classes = 
            UnivClass
                .with_univ_class_details

        if params[:level].present? && params[:day].present? && params[:period].present?
            # @univ_classes = UnivClass.where(level: params[:level])
            days = params[:day]=="All" ? ["月", "火", "水", "木", "金"] : params[:day]
            periods = params[:period]=="All" ? ["1", "2", "3", "4", "5"] : params[:period]
            levels = params[:level] == "All" ? UnivClass.pluck(:level).uniq :  params[:level]
            @univ_classes = UnivClass.with_same_day_and_period_without_user(days, periods, levels)

            unless params[:day]=="All" then
                day_index =  ["月", "火", "水", "木", "金", "All"].index(params[:day])
                @day = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "All Classes"][day_index]
            end
            unless params[:period]=="All" then
                @period = params[:period].to_i.ordinalize+" Period"
            end
            unless params[:level]=="All" then
                @level = params[:level].split('_').map {|ele| ele=="II" ? ele : ele.capitalize }.join(' ')
            end
            @sentence = [@day, @period, @level].compact.join(" | ")
        elsif params[:level].present?
            levels = params[:level] == "All" ? UnivClass.pluck(:level).uniq : params[:level]
            @univ_classes = UnivClass.joins(:univ_class_details).where(level: levels)
            @sentence = params[:level].split('_').map {|ele| ele=="II" ? ele : ele.capitalize }.join(' ')
        else
            @univ_classes = UnivClass.all
            @sentence = "All Classes"
        end
    end
    
    def update
        @user = User.find(params[:user_id])
        @univ_class = UnivClass.find(params[:id])
        extreme = params[:extreme]
        if extreme == "1"
            existing_classes = UnivClass.with_same_day_and_period_with_user(@user.id, @univ_class.univ_class_details.pluck(:day), @univ_class.univ_class_details.pluck(:period))
            existing_classes.update_all(user_id: nil)
            @univ_class.update(update_params)
            flash[:success] = "Successfully Added to Your Time Schedule"
            redirect_to user_path(@user)
        elsif extreme == "0"
            @univ_class.update(update_params)
            flash[:success] = "Successfully Added to Your Time Schedule"
            redirect_to user_path(@user)
        else
            flash[:error] = "Something Happened."
            render 'index'
        end
    end
    
    def show
        @user = User.find(params[:user_id])
        @univ_class = UnivClass.find(params[:id])
        gon.user_id = @user.id
        gon.univ_class_id = @univ_class.id
        @existing_classes = UnivClass.with_same_day_and_period_with_user(@user.id, @univ_class.univ_class_details.pluck(:day), @univ_class.univ_class_details.pluck(:period))
    end

    def destroy
        @user = User.find(params[:user_id])
        @univ_class = UnivClass.find(params[:id])
        if @univ_class.update(user_id: nil)
            flash[:success] = "Successfully Removed from Your Time Schedule"
            redirect_to user_path(@user)
        else
            flash[:error] = "Something Happened."
            render 'show'
        end
    end
    
    # def import
    #     UnivClass.import(params[:file])
    #     redirect_to root_path, notice: 'Successfully imported #{params[:file]}'
    # end
    
    def search
        @user = User.find(params[:user_id])
        @univ_class = UnivClass.find_by(subject_name: params[:subject_name])
        if @univ_class
            render :show
        else
            flash[:error] = "Couldn't find a class with name: "  + params[:subject_name]
            redirect_to :root_path
        end
    end
    
    private
    
    def update_params
        params
            .permit(:id, :user_id)
    end
end



#usable??
        # elsif params[:day].present? && params[:period].present?
        #     day = params[:day]=="All" ? ["月", "火", "水", "木", "金"] : params[:day]
        #     period = params[:period]=="All" ? ["1", "2", "3", "4", "5"] : params[:period]
        #     @univ_classes = UnivClass.with_same_day_and_period_without_user(day, period)
        #     day_index =  ["月", "火", "水", "木", "金", "All"].index(params[:day])
        #     @day = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "All Classes"][day_index]
        #     @period = period
        # elsif params[:day].present?
        #     @univ_classes = UnivClass.with_same_day(params[:day])
        #     day_index =  ["月", "火", "水", "木", "金"].index(params[:day])
        #     @day = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"][day_index]

app/views/univ_classes/index.html.erb
<!--<table>-->
<div class="container">
    <div class="panel panel-info detailed-search">
        <div class="panel-heading">
            <h3>Detailed Search</h3>
        </div>
        <div class="panel-body">
            <div class="dropdown-detailed-search" style="display: inline-block; width:250px;">
                <div class="dropdown-day">
                    <div class="dropdown col-xs-12">
                    	<button class="btn btn-default dropdown-toggle detailed-search" disable="true" type="button" data-toggle="dropdown" data-target="day">
                    		Select Day<span class="caret" style="margin-left: 10px;"></span>
                    	</button>
                    	<ul class="dropdown-menu" role="menu">
                    		<li role="presentation"><a tabindex="-1" href="javascript:void(0)">Mon</a></li>
                    		<li role="presentation"><a tabindex="-1" href="javascript:void(0)">Tues</a></li>
                    		<li role="presentation"><a tabindex="-1" href="javascript:void(0)">Wed</a></li>
                    		<li role="presentation"><a tabindex="-1" href="javascript:void(0)">Thurs</a></li>
                    		<li role="presentation"><a tabindex="-1" href="javascript:void(0)">Fri</a></li>
                    		<li role="presentation"><a tabindex="-1" href="javascript:void(0)">All</a></li>
                    	</ul>
                    </div>
                </div>
            </div>
            <div class="dropdown-detailed-search" style="display: inline-block; width:250px;">
                <div class="dropdown-period">
                    <div class="dropdown col-xs-12">
                    	<button class="btn btn-default dropdown-toggle detailed-search" type="button" data-toggle="dropdown" data-target="period">
                    	    Select Period<span class="caret" style="margin-left: 10px"></span>
                    	</button>
                    	<ul class="dropdown-menu" role="menu">
                    		<li role="presentation"><a href="javascript:void(0)">1</a></li>
                    		<li role="presentation"><a href="javascript:void(0)">2</a></li>
                    		<li role="presentation"><a href="javascript:void(0)">3</a></li>
                    		<li role="presentation"><a href="javascript:void(0)">4</a></li>
                    		<li role="presentation"><a href="javascript:void(0)">5</a></li>
                    		<li role="presentation"><a href="javascript:void(0)">All</a></li>
                    	</ul>
                    </div>
                </div>
            </div>
            <div class="dropdown-detailed-search" style="display: inline-block; width:250px;">
                <div class="dropdown-level">
                    <div class="dropdown col-xs-12">
                    	<button class="btn btn-default dropdown-toggle detailed-search" type="button" data-toggle="dropdown" data-target="period">
                    	    Select Level<span class="caret" style="margin-left: 10px"></span>
                    	</button>
                    	<ul class="dropdown-menu" role="menu">
                    		<li role="presentation"><a href="javascript:void(0)">Language</a></li>
                    		<li role="presentation"><a href="javascript:void(0)">First Year Seminar I</a></li>
                    		<li role="presentation"><a href="javascript:void(0)">First Year Seminar II</a></li>
                    		<li role="presentation"><a href="javascript:void(0)">Intermediate Seminar</a></li>
                    		<li role="presentation"><a href="javascript:void(0)">Introductory Course</a></li>
                    		<li role="presentation"><a href="javascript:void(0)">Intermediate Course</a></li>
                    		<li role="presentation"><a href="javascript:void(0)">Advanced Course</a></li>
                    		<li role="presentation"><a href="javascript:void(0)">Other Course</a></li>
                    		<li role="presentation"><a href="javascript:void(0)">All</a></li>
                    	</ul>
                    </div>
                </div>
            </div>
            <div class="dropdown-detailed-search" style="display: inline-block;">
                <input type="button" onclick='"#"' value="Search!" class="btn btn-primary detailed-search-button" id="detailed-search-button"/>
        	</div>
        </div>
    </div>
</div>
<table class="table table-hover">
    <thead>
        <tr>
            <th>Course Code</th>
            <th>Subject Name</th>
            <th>Professor</th>
            <th>Day & Period</th>
            <th>Classroom</th>
        </tr>
        <tbody>
            <h1 class="class-info-bar">
                <%= @sentence %>
            </h1>
            <h4 class="univ-class-counter">
                <% if @univ_classes.count > 1 %>
                    Result: <%= @univ_classes.count %> classes found
                <% else %>
                    Result: <%= @univ_classes.count %> class found
                <% end %>
            </h4>
            <% @univ_classes.each do |univ_class| %>
                <% if @user.present? %>
                    <tr onclick='window.location="<%= user_univ_class_path(@user.id, univ_class.id) %>"', role="link">
                <% else %>
                    <tr>
                <% end %>
                    <th><%= univ_class.class_code %></th>
                    <th><%= univ_class.subject_name %></th>
                    <th><%= univ_class.professor %></th>
                    <th>
                        <% univ_class.univ_class_details.pluck(:day, :period).each do |detail| %>
                            <h5><%= detail[0]%>, <%= detail[1] %></h5>
                        <% end %>
                    </th>
                    <th><%= univ_class.univ_class_details[0].classroom %></th>
                </tr>
            <% end %>
        </tbody>
    </thead>
</table>
<!--<div>-->
<!--    <h4>Import</h4>-->
<!--    <= form_tag univ_classes_import_path, multipart: true do %>-->
<!--        <= file_field_tag :file %>-->
<!--        <= submit_tag "import csv" %>-->
<!--    < end %>-->
<!--</div>-->

<style>
    .class-info-bar {
        margin-bottom: 30px;
        border-bottom: 3px double;
    }
    .univ-class-counter {
        margin-bottom: 15px;
        border-bottom: 1px solid;
    }
    .panel.panel-info.detailed-search {
        width: 1100px !important;
    }
    /*dropdown box*/
    .btn.btn-default.dropdown-toggle.detailed-search {
        width: 200px !important;
        margin-left: 30px !important;
    }
    .btn.btn-primary.detailed-search-button {
        /*background-color: #f44336;*/
        width: 150px;
        vertical-align: middle;
        margin-bottom: 27px;
        margin-left: 80px;
    }
    /*.dropdown-detailed-search {*/
    /*   display: inline-block !important;*/
    /*}*/
    .slash{
        font-size: 30px;
        margin-left: 50px;
        margin-right: 50px;
    }
</style>

<script>

    $(".dropdown-level .dropdown .dropdown-menu li a").click(function(){
        $(".btn:first-child")[2].innerHTML = $(this).text() + '<span class="caret" style="margin-left: 10px"></span>';
        if ($(".btn:first-child")[0].innerHTML.split('<')[0].replace(/\r?\n/g,"").trim() == "Select Day") {  $(".btn:first-child")[0].innerHTML = 'All' + '<span class="caret" style="margin-left: 10px"></span>'}
        var day = $(".btn:first-child")[0].innerHTML.split('<')[0];
        if ($(".btn:first-child")[1].innerHTML.split('<')[0].replace(/\r?\n/g,"").trim() == "Select Period") {  $(".btn:first-child")[1].innerHTML = 'All' + '<span class="caret" style="margin-left: 10px"></span>'}
        var period = $(".btn:first-child")[1].innerHTML.split('<')[0];
        var level = $(".btn:first-child")[2].innerHTML.split('<')[0];
        struct_link(day_convertor(day), period, level_convertor(level));
    });

    $(".dropdown-period .dropdown .dropdown-menu li a").click(function(){
        $(".btn:first-child")[1].innerHTML = $(this).text() + '<span class="caret" style="margin-left: 10px"></span>';
        var period = $(this).text();
        if ($(".btn:first-child")[0].innerHTML.split('<')[0].replace(/\r?\n/g,"").trim() == "Select Day") {  $(".btn:first-child")[0].innerHTML = 'All' + '<span class="caret" style="margin-left: 10px"></span>'}
        var day = $(".btn:first-child")[0].innerHTML.split('<')[0];
        if ($(".btn:first-child")[2].innerHTML.split('<')[0].replace(/\r?\n/g,"").trim() == "Select Level") { $(".btn:first-child")[2].innerHTML = 'All' + '<span class="caret" style="margin-left: 10px"></span>'}
        var level = $(".btn:first-child")[2].innerHTML.split('<')[0];
        struct_link(day_convertor(day), period, level_convertor(level));
    });

    $(".dropdown-day .dropdown .dropdown-menu li a").click(function(){
        $(".btn:first-child")[0].innerHTML = $(this).text() + '<span class="caret" style="margin-left: 10px"></span>';
        var day = $(this).text();
        if ($(".btn:first-child")[1].innerHTML.split('<')[0].replace(/\r?\n/g,"").trim() == "Select Period") {  $(".btn:first-child")[1].innerHTML = 'All' + '<span class="caret" style="margin-left: 10px"></span>'}
        var period = $(".btn:first-child")[1].innerHTML.split('<')[0];
        if ($(".btn:first-child")[2].innerHTML.split('<')[0].replace(/\r?\n/g,"").trim() == "Select Level") { $(".btn:first-child")[2].innerHTML = 'All' + '<span class="caret" style="margin-left: 10px"></span>'}
        var level = $(".btn:first-child")[2].innerHTML.split('<')[0];
        struct_link(day_convertor(day), period, level_convertor(level) );
    });
    
    function struct_link(day='All', period='All', level='All') {
        // ### SELECT PERIOD ###
        <% if @user.nil? %>
            var text = "#"
            return text;
        <% else %>
            var text = "/users/<%= @user.id %>/univ_classes?day="+day+"&period="+period+"&level="+level
            document.getElementById("detailed-search-button").attributes[1].value =`window.location="${text}"`;
            console.log(text);
            return text;
        <% end %>
    }
    
    function day_convertor(day) {
        var day_convertor = {"Mon" : "月", "Tues" : "火", "Wed" : "水", "Thurs" : "木", "Fri" : "金", "Select Day" : "All"};
        return day_convertor[day]
    }
    
    function level_convertor(level) {
        var level_convertor = { "Language" : "language", 
            "First Year Seminar I" : "first_year_seminar_I", 
            "First Year Seminar II" : "first_year_seminar_II",
            "Intermediate Seminar" : "intermediate_seminar",
            "Advanced Seminar" : "Advanced Seminar",
            "Introductory Course" : "introductory_course",
            "Intermediate Course" : "intermediate_course",
            "Advanced Course" : "advanced_course",
            "Other Course" : "other_course",
            "All" : "All",
            "Select All" : "All"
        }
        return level_convertor[level]
    }
</script>

app/views/univ_classes/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <div class="favorite-class">
      <h3>Class Information</h3>
    </div>
    <div class="favorite-class">
      <div id="like-button">
        <% if @univ_class.likes&.pluck(:user_id).include?(@user.id) %>
          <%= link_to user_univ_class_likes_path(@user, @univ_class), method: :delete, id: "like-button-delete", remote: true do %>
            <i class="fas fa-star"></i><span style="font-size:14px;color:yellow;margin-left:10px">Remove from Your List!</span>
          <% end %>
        <% else %>
          <%= link_to user_univ_class_likes_path(@user, @univ_class), method: :post, remote:true, id: "like-button-post" do %>
            <i class="far fa-star"></i><span style="font-size:14px;color:yellow;margin-left:10px">Add to Your List!</span>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
    <div class="panel-bodys">
      <h1 class="class-detail-info"><%= @univ_class.subject_name %></h1>
      <h5 class="class-detail-info-s">
        Level:
          <font style="padding-left: 90px" size=4><%= @univ_class.level.split('_').map {|ele| ele=="II" ? ele : ele.capitalize }.join(' ') %></font>
      </h5>
      <h5 class="class-detail-info-s">
        Professor:  <font  style="padding-left: 60px" size=4><%= @univ_class.professor %></font>
      </h5>
      <h5 class="class-detail-info-s">
        Day & Period:  
        <% @univ_class.univ_class_details.pluck(:day, :period).each do |detail| %>
            <font style="padding-left: 40px" size=4><%= ["Mon", "Tues", "Wed", "Thurs", "Fri", "Sat"][ ["月", "火", "水", "木", "金", "土"].index(detail[0]) ] %>, <%= detail[1] %></font>
        <% end %>
      </h5>
      <h5 class="class-detail-info-s">
        Classroom:  <font style="padding-left: 55px" size=4><%= @univ_class.univ_class_details[0].classroom %></font>
      </h5>
      <h5 class="class-detail-info-s">
        Number of Credit:  <font style="padding-left: 15px" size=4><%= @univ_class.number_of_credit %></font>
      </h5>
      <h5 class="class-detail-info-s class-detail-info-paragraph">
        Explanation:  <font style="padding-left: 55px" size=4><p class="class-detail-info-s"><%= @univ_class.content_of_class %><p></p></font>
      </h5>
      <h5 class="class-detail-info-evaluation-beginning"> Evaluation: </h5>
      <h5 class="class-detail-info-evaluation">
        Exam:  <font style="padding-left: 85px" size=4><p class="class-detail-info-evaluation"><%= @univ_class.exam_evaluation&.remove("試験:") %></p></font>
      </h5>
      <h5 class="class-detail-info-evaluation">
        Essay: <font style="padding-left: 55px" size=4><p class="class-detail-info-evaluation"><%= @univ_class.report_evaluation %></p></font>
        </div>
      </h5>
      <h5 class="class-detail-info-evaluation">
        Attendence: <font style="padding-left: 55px" size=4><p class="class-detail-info-evaluation"><%= @univ_class.normal_evaluation %></p></font>
      </h5>
      <h5 class="class-detail-info-evaluation">
        Other: <font style="padding-left: 55px" size=4><p class="class-detail-info-evaluation"><%= @univ_class.other_evaluation&.remove("備考・関連URL") %></p></font>
      </h5>
      <h5 class="class-detail-info-class_url">
        <a href="<%= @univ_class.class_url %>", target="right">Jump to Class Website</a>
      </h5>
      <div class="class-detail-info-button">
        <% if @univ_class.user == @user %>
          <%= link_to "Remove from Your Schedule", user_univ_class_path(@user, @univ_class, :extreme => 0), method: :delete, class: "btn btn-danger class-detail-info" %>
        <% elsif @existing_classes.present? %>
          <div class="alert alert-warning">
            <strong>Warning!</strong> You alreay registered some classes on the same day and period. You should <%= link_to "check your schedule", user_path(@user)%>.
          </div>
          <p>Do you want to replace with existing classes? <%= link_to "Replace with Existing Clases", user_univ_class_path(@user, @univ_class, :extreme => 1), method: :patch, class: "btn btn-info"%> </p>
          <p>Do you want to add the class with existing classes? <%= link_to "Add with Existing Clases", user_univ_class_path(@user, @univ_class, :extreme => 0), method: :patch, class: "btn btn-primary" %></p>
         <!--elsif @univ_class.user != @user %>-->
        <% else %>
          <%= link_to "Add To Your Schedule", user_univ_class_path(@user, @univ_class, :extreme => 0), method: :patch, class: "btn btn-primary class-detail-info" %>
        <% end %>
      </div>
  </div>
</div>

<style>
.class-detail-info {
  text-align: center;
  border-bottom: thin inset powderblue;
}
.class-detail-info-s {
  margin-left: 200px;
  padding-top: 10px;
}
.class-detail-info-paragraph {
  display: block;
}
p.class-detail-info-s {
  margin-left: 30px;
  margin-right: 100px;
}
p.class-detail-info-evaluation {
  margin-left: 30px;
  margin-right: 100px;
  padding-top: 10px;
}
.class-detail-info-evaluation-beginning {
  margin-left: 200px;
  margin-top: -20px;
}
.class-detail-info-evaluation {
  margin-left: 220px;
  margin-bottom: -15px;
}
.class-detail-info-class_url {
  margin-left: 200px;
  padding-top: 30px;
}
.btn.btn-danger.class-detail-info {
  text-align: center;
}
.btn.btn-primary.class-detail-info {
  text-align: center;
}

.class-detail-info-button {
  text-align: center;
  margin-top: 30px;
  margin-bottom: 30px;
}
.fas {
  color: yellow;
  font-size: 15px;
  margin-left: 50px;
}
.far {
  color: yellow;
  font-size: 15px;
  margin-left: 50px;
}
.favorite-class {
  display: inline-block;
}
</style>