config/routes.rb
Rails.application.routes.draw do
  devise_for :user
  get '/user', to: redirect("/user/sign_up"), as: "user_sign_up_again"

  root to: "home#index"
  
  resources :univ_classes, only: [:index]

  resources :users, only: [:show] do
    resource :likes, only: [:show]
    resources :univ_classes, only: [:index, :show, :update, :destroy] do
      resource :likes, only: [:create, :destroy]
      collection do
        get :search
      end
    end
  end
  post "/univ_classes/import", to: 'univ_classes#import'
  #/users/:id/univ_classes/search　これはエラー。users/:user_id/univ_classes/searchじゃないとだめ！！idはuniv_class_idと認識されてしまう。注意
  # get "/users/:id/univ_classes/search", to: 'univ_classes#search'
  
  # get '*path', controller: 'application', action: 'render_404'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jikanwari</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'app_logo.png' %>
    <%= Gon::Base.render_data %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
            <%= link_to "Timeline Scheduler", root_path, class: "navbar-brand" %>
        </div>
        
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
    				<li>
              <% if current_user %>
                <%= link_to "Your Timeline", user_path(current_user) %>
              <% end %>
            </li>
            <li class='dropdown'>
              <a href='#' class='dropdown-toggle' data-toggle='dropdown'>
                Course List <span class='caret'></span>
              </a>
              <ul class='dropdown-menu'>
                <li>
                  <% if current_user %>
                    <%= link_to "Language", user_univ_classes_path(current_user, :level => 'language') %>
                  <% else %>
                    <%= link_to "Language", univ_classes_path(:level => 'language') %>
                  <% end %>
                </li>
                <li class='divider'></li>
                <li>
                  <% if current_user %>
                    <%= link_to "First Year Seminar I", user_univ_classes_path(@user, :level => 'first_year_seminar_I') %>
                  <% else %>
                    <%= link_to "First Year Seminar I", univ_classes_path(:level => 'first_year_seminar_I') %>
                  <% end %>
                </li>
                <li class='divider'></li>
                <li>
                  <% if current_user %>
                    <%= link_to "First Year Seminar II", user_univ_classes_path(@user, :level => 'first_year_seminar_II') %>
                  <% else %>
                    <%= link_to "First Year Seminar II", univ_classes_path(:level => 'first_year_seminar_II') %>
                  <% end %>
                </li>
                <li class='divider'></li>
                <li>
                  <% if current_user %>
                    <%= link_to "Intermediate Seminar", user_univ_classes_path(@user, :level => 'intermediate_seminar') %>
                  <% else %>
                    <%= link_to "Intermediate Seminar", univ_classes_path(:level => 'intermediate_seminar') %>
                  <% end %>
                </li>
                <li class='divider'></li>
                <li>
                  <% if current_user %>
                    <%= link_to "Advanced Seminar", user_univ_classes_path(@user, :level => 'advanced_seminar') %>
                  <% else %>
                    <%= link_to "Advanced Seminar", univ_classes_path(:level => 'advanced_seminar') %>
                  <% end %>
                </li>
                <li class='divider'></li>
                <li>
                  <% if current_user %>
                    <%= link_to "Introductory Course", user_univ_classes_path(@user, :level => 'introductory_course') %>
                  <% else %>
                    <%= link_to "Introductory Course", univ_classes_path(:level => 'first_year_seminar_I') %>
                  <% end %>
                </li>
                <li class='divider'></li>
                <li>
                  <% if current_user %>
                    <%= link_to "Intermediate Course", user_univ_classes_path(@user, :level => 'intermediate_course') %>
                  <% else %>
                    <%= link_to "Intermediate Course", univ_classes_path(:level => 'intermediate_seminar') %>
                  <% end %>
                </li>
                <li class='divider'></li>
                <li>
                  <% if current_user %>
                    <%= link_to "Advanced Course", user_univ_classes_path(@user, :level => 'advanced_course') %>
                  <% else %>
                    <%= link_to "Advanced Course", univ_classes_path(:level => 'advanced_course') %>
                  <% end %>
                </li>
                <li class='divider'></li>
                <li>
                  <% if current_user %>
                    <%= link_to "Other Course", user_univ_classes_path(@user, :level => 'other_course') %>
                  <% else %>
                    <%= link_to "Other Course", univ_classes_path(:level => 'other_course') %>
                  <% end %>
                </li>
              </ul>
            </li>
            <li>
              <% if current_user %>
                <%= link_to "Your List", user_likes_path(@user), method: :get%>
              <% end %>
            </li>
    			</ul>
	
	        <form class="navbar-form navbar-left" role="search" action="/action_page.php">
            <div class="form-group">
              <%= select_tag 'searchDropdownBox', options_for_select(UnivClass.all.map(&:subject_name)), class: "searchable", include_blank: "Search By Subject Name", style: "width:400px; height:30px;" %>
            </div>
            <% if current_user %>
              <input type="button" onclick='"#"' value="Submit" class="btn btn-info" id="search-by-subject-button"/>
            <% else %>
              <%= link_to "Submit", new_user_session_path, class: "btn btn-info" %>
            <% end %>
          </form>
          
          
          <div class="navbar-text navbar-right">
            <% if user_signed_in? %>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <span class="glyphicon glyphicon-user">Logout</span>
                <% end %>
            <% else %>
                <%= link_to new_user_session_path do %>
                  <span class="glyphicon glyphicon-user">Login</span>
                <% end %>
            <% end %>
          </p>

        </div>

      </div>
    </nav>

    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %> alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <%= value %>
      </div>
    <% end %>
    <%= yield %>
    
    <style>
      html,
      body {
        overflow-y:scroll;
        font-family: 'Varela Round';
      }
      a.navbar-brand {
        color: white !important;
      }
    </style>

    <script>
      $(function() {
        return $(".searchable").select2({
        });
      });
      
      $('#searchDropdownBox').on('select2:select', function (e) {
          var data = e.params.data;
          <% if @user.present? %>
            document.getElementById("search-by-subject-button").attributes[1].value = `window.location="/users/<%= @user.id %>/univ_classes/search?subject_name=${data.text}"`;
          <% else %>
            document.getElementById("search-by-subject-button").attributes[1].value = `window.location="univ_classes/search?subject_name=${data.text}"`;
          <% end %>
          console.log(document.getElementById("search-by-subject-button").attributes[1].value);
      });

    </script>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Jikanwari</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <%= favicon_link_tag 'app_logo.png' %>
    
     <!--Bootstrap 4  TODO: Migrate to bootstrap4 -->
    <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">-->
    <!--<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>-->

     <!--Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    
    <!-- Bootstrap core JavaScript -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag    'home', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'home', 'data-turbolinks-track': 'reload' %>
     <!--Bootstrap 4  TODO: Migrate to bootstrap4 -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>

  <%= yield %>
</html>